#spring.application.name=api-monitoring
#
## ===============================
## SERVER
## ===============================
#server.port=8080
#
## ===============================
## DATASOURCE - POSTGRESQL LOCAL
## ===============================
#spring.datasource.url=jdbc:postgresql://localhost:5432/api_monitoring
#spring.datasource.username=mauriciogabriel
#spring.datasource.password=
#spring.datasource.driver-class-name=org.postgresql.Driver
#
## ===============================
## JPA / HIBERNATE
## ===============================
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=false
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#
## ===============================
## TASK MONITORING
## ===============================
#task.watchdog.monitoring.enabled=true

server.port=${PORT:8080}

## ===============================
## DATASOURCE - POSTGRESQL CLOUD
## ===============================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://dpg-d6qu5gvafjfc73etu9b0-a.oregon-postgres.render.com:5432/api_monitoring_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:api_monitoring_db_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:b4jQP7FFM2CWacURtVMv601Bg0956ORm}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.database-platform=${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.dialect.PostgreSQLDialect}
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

task.watchdog.monitoring.enabled=${TASK_WATCHDOG_ENABLED:true}
task.watchdog.monitoring.delay=${TASK_WATCHDOG_DELAY:5000}

timeout.connect=${CONNECT_TIMEOUT_MILLIS:5000}
timeout.answer=${ANSWER_TIMEOUT_SECONDS:5}
timeout.read=${READ_TIMEOUT_SECONDS:5}
timeout.write=${WRITE_TIMEOUT_SECONDS:5}

